### ISSUE TITLE
Model reporting for iterative comparisons

### ISSUE THREAD

**Issue by emmamendelsohn** [One-Health-Research-Consulting/open-rvfcast#5]
```[tasklist]
### Tasks
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/69
- [ ] Model diagnostics and interpretation (e.g., test data performance, mcmc chains, variable importance)
- [ ] Real time predictions (e.g., maps, figures/maps showing which variables are most contributing to predictions, rolling look at predictions and actual conditions since model was fit). Example map showing relative contribution of variables by pixel: https://www.mdpi.com/2078-1547/13/2/66#B52-challenges-13-00066
- [ ] Model accuracy metrics
```

**Comment by emmamendelsohn** [comment]
In general, this should be a report that is generated along with the first model version to enable comparison as you iterate on the model.

**Comment by emmamendelsohn** [comment]
This might be helpful from REPEL where we used `relic` to compare model updates: https://github.com/ecohealthalliance/repel2/blob/dev/reports/repel_model_iterative_comparison_checks.Rmd. The model statistics are different from REPEL (lme4) but the comparison framework may or may not be useful.
