### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by emmamendelsohn** [One-Health-Research-Consulting/open-rvfcast#91]
This is roughly the order I imagine addressing things. I wouldn't spend too much time on the data before the model. You can bring in additional variables after the fact. This road map includes all issues in this repo except for those labeled as enhancements. (I suggest reviewing the enhancement issues for ideas about future steps as well as current limitations.)

Please make sure you read the linked issues all the way through, as some are old threads where we have changed course along the way.

```[tasklist]
### Priority Tasks
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/92
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/95
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/5
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/20
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/90
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/94
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/82
```

```[tasklist]
### Prediction and automation tasks
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/93
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/7
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/89
```

```[tasklist]
### Issues that will arise when moving beyond RSA
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/72
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/75
```

**Comment by morgankain** [comment]
Very old issue where lots of the issues this references are now closed. Probably sensible to reopen a new updated list given all of the progress that has been made
